### ISSUE TITLE
非常优秀,没有之一,另外

### ISSUE THREAD

**Issue by Vc-great** [lipengzhou/typora-theme-auto-numbering#1]
你写的自动编号,比我之前用的那些都好;
还有个请求,可以的话能分享你的主题么;
网上找了很多主题,都不是很理想,感谢

**Comment by lipengzhou** [comment]
使用就是默认的 GitHub 主题，我稍微做了一些修改，修改之后的主题文件就是这个仓库中的 `github.user.css` 文件，你把它也拷贝到你的主题目录中就可以了。

**Comment by Honeylemonade** [comment]
感谢作者
