### ISSUE TITLE
缺失二级标题后，标注的编号有问题

### ISSUE THREAD

**Issue by BrambleXu** [lipengzhou/typora-theme-auto-numbering#2]
图片里 `数学函数/算数函数/统计函数`使用的是一级标题，而`numpy sum`是三级标题。于是导致编号错误。内容里的编号和大纲里的编号不一样。

![image](https://user-images.githubusercontent.com/10768193/53104306-7ced9680-3572-11e9-94eb-c69ab7aaf1ab.png)

而TOC的显示也不正常，`数学函数/算数函数/统计函数`下面的部分都没有显示

![image](https://user-images.githubusercontent.com/10768193/53104716-3cdae380-3573-11e9-9777-f8a8ff48ea5f.png)

添加二级标题后正常

![image](https://user-images.githubusercontent.com/10768193/53104459-bb835100-3572-11e9-9062-162e2fdccda2.png)

希望能在确实某一级标题的情况下，左侧大纲的部分，起码显示不同的编号。

**Comment by lipengzhou** [comment]
一个合理的文档结构应该是下面这样的：

```
一级标题（一篇文档中有且仅有最大的一个标题）

二级标题（属于一级，在一级标题之下）

三级标题（属于父亲二级标题）

三级标题（属于父亲二级标题）

二级标题（属于一级，在一级标题之下）

三级标题（属于父亲二级标题）

三级标题（属于父亲二级标题）

二级标题（属于一级，在一级标题之下）

三级标题（属于父亲二级标题）

三级标题（属于父亲二级标题）

依次类推
```

当你直接在一级标题下方出现非二级标题的时候就会出现你文中的情况，并非主题编号的问题，结构本身的不合理用任何工具都没有作用，因为所谓的自动都必须有规则，没有规则就无法自动。

另外推荐一下一个良好的 Markdown 标题目录规则：

```markdown
# 一级标题（不参与编号）

## 二级标题（1）

### 三级标题（1-1）

#### 四级标题（1-1-1）


### 三级标题（1-2）

### 三级标题（1-3）

##  二级标题（2）

### 三级标题（2-1）

### 三级标题（2-2）

### 三级标题（2-3）

## 二级标题 （3）

### 三级标题（3-1）

### 三级标题（3-2）

### 三级标题（3-3）
```
