### ISSUE TITLE
一级标题不编号吗？

### ISSUE THREAD

**Issue by youthlql** [lipengzhou/typora-theme-auto-numbering#3]
![image](https://user-images.githubusercontent.com/49017153/103755362-aae60200-5048-11eb-8bd9-dca226ee0ea5.png)
![image](https://user-images.githubusercontent.com/49017153/103755373-afaab600-5048-11eb-9a9c-c4c86318e974.png)
为什么有的文档可以，有的文档不可以。而且是有的目录可以，有的目录不可以？

**Comment by HelloWarcraft** [comment]
> ![image](https://user-images.githubusercontent.com/49017153/103755362-aae60200-5048-11eb-8bd9-dca226ee0ea5.png)
> ![image](https://user-images.githubusercontent.com/49017153/103755373-afaab600-5048-11eb-9a9c-c4c86318e974.png)
> 为什么有的文档可以，有的文档不可以。而且是有的目录可以，有的目录不可以？

为什么你的这个背景看着这么花哨啊，给俺也整一个好不

**Comment by youthlql** [comment]
> > ![image](https://user-images.githubusercontent.com/49017153/103755362-aae60200-5048-11eb-8bd9-dca226ee0ea5.png)
> > ![image](https://user-images.githubusercontent.com/49017153/103755373-afaab600-5048-11eb-9a9c-c4c86318e974.png)
> > 为什么有的文档可以，有的文档不可以。而且是有的目录可以，有的目录不可以？
> 
> 为什么你的这个背景看着这么花哨啊，给俺也整一个好不

好像是一个叫orange-heart的主题
