### ISSUE TITLE
导出pdf侧边栏都没有编号了

### ISSUE THREAD

**Issue by pokitpeng** [lipengzhou/typora-theme-auto-numbering#4]
![image](https://user-images.githubusercontent.com/38129494/122660486-8cb62d80-d1b4-11eb-8349-e4cb76c20bb9.png)

**Comment by sumht** [comment]
你好 这个pdf导出编号有解决方案了吗

**Comment by pokitpeng** [comment]
> 

没有，我没用了，转vscode了
